[Actions] Adding a MacOS build workflow and making sure it is warning-free (#395)
* Add a macOS build template

* Create the build workflow

* For now let's call the workflow on each push

* Make sure to build on this branch on calls from different repos

* No need for the venv and jsonref here

* Remove the architecture specification in the cmake build command

* Correct the venv path

* For now let's disable the shift-count-overflow warning

In file included from /Users/runner/work/ThunderInterfaces/ThunderInterfaces/ThunderInterfaces/interfaces/IDRM.h:49:
/Users/runner/work/ThunderInterfaces/ThunderInterfaces/ThunderInterfaces/interfaces/../interfaces/DRMHelper.h:54:21: error: shift count >= width of type [-Werror,-Wshift-count-overflow]
                tmp <<= 8;
                    ^   ~
/Users/runner/work/ThunderInterfaces/ThunderInterfaces/ThunderInterfaces/interfaces/../interfaces/DRMHelper.h:81:68: note: in instantiation of function template specialization 'BufferReader::Read<unsigned char>' requested here
    inline bool Read1(uint8_t* v) WARNING_RESULT_NOT_USED { return Read(v); }
                                                                   ^
1 error generated.

* Add a PUSH_WARNING_ARG_

* No need to build this repo with and without static linking

* Remove the shared libs matrix in the workflow file

* Add a separate logic for Read1(uint8_t) without the loop and shifting

* Change the venv path to match the Linux templates

* Use the workflows from master branches

* Checkout the master branch instead of develop